import {Food} from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';

export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'Dal Makhani',
    cookTime: '20-30',
    price: 230,
    favorite: false,
    origins: ['North Indian'],
    stars: 4.5,
    imageUrl: 'assets/dalM.jpg',
    tags: ['North Indian', 'Lunch'],
  },
  {
    id:'2',
    name: 'Hyderabadi Biryani',
    price: 200,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'India'],
    stars: 4.7,
    imageUrl: 'assets/biryani.jpg',
    tags: ['Rice', 'Lunch'],
  },
  {
    id:'3',
    name: 'Burrata Salad',
    price: 175,
    cookTime: '10-15',
    favorite: false,
    origins: ['Germany', 'Indian'],
    stars: 3.5,
    imageUrl: 'assets/burrata-salad.jpg',
    tags: ['Salad', 'Lunch'],
  },
  {
    id:'4',
    name: 'Vada Sambar',
    price: 85,
    cookTime: '15-20',
    favorite: true,
    origins: ['South Indian'],
    stars: 3.3,
    imageUrl: 'assets/VS.jpg',
    tags: ['South Indian', 'Fry'],
  },
  {
    id:'5',
    name: 'Mojito',
    price: 110,
    cookTime: '20-30',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 5.0,
    imageUrl: 'assets/mojito.jpg',
    tags: ['Salad', 'Soup'],
  },
  {
    id:'6',
    name: 'Rajma Chawal',
    price: 190,
    cookTime: '40-50',
    favorite: false,
    origins: ['North Indian'],
    stars: 5.0,
    imageUrl: 'assets/RC.jpg',
    tags: ['North Indian', 'Rice', 'Lunch'],
  },
  {
    id:'7',
    name: 'Tomato Onion Uthappam',
    price: 120,
    cookTime: '20-30',
    favorite: false,
    origins: ['South Indian'],
    stars: 4.0,
    imageUrl: 'assets/utt.jpg',
    tags: ['South Indian', 'Lunch'],
  },
  {
    id:'8',
    name: ' Garlic Butter Naan',
    price: 50,
    cookTime: '15-20',
    favorite: false,
    origins: ['North Indian'],
    stars: 4.0,
    imageUrl: 'assets/naan.jpg',
    tags: ['Breads',  'Lunch'],
  },
  {
    id:'9',
    name: 'Paneer Butter Masala',
    price: 190,
    cookTime: '45-50',
    favorite: false,
    origins: ['North Indian'],
    stars: 4.0,
    imageUrl: 'assets/pbm.jpg',
    tags: ['North Indian',  'Lunch'],
  },
  {
    id:'10',
    name: 'Shahi Paneer',
    price: 220,
    cookTime: '45-50',
    favorite: false,
    origins: ['North Indian'],
    stars: 4.0,
    imageUrl: 'assets/shahi.jfif',
    tags: ['North Indian',  'Lunch'],
  },
  {
    id:'11',
    name: 'Tomato Soup',
    price: 120,
    cookTime: '45-50',
    favorite: false,
    origins: ['North Indian'],
    stars: 4.0,
    imageUrl: 'assets/soup2.jpg',
    tags: ['Soup',  'Lunch'],
  },
  {
    id:'12',
    name: 'Tandoori Roti',
    price: 20,
    cookTime: '5-10',
    favorite: false,
    origins: ['North Indian'],
    stars: 4.0,
    imageUrl: 'assets/roti.jfif',
    tags: ['Breads',  'Lunch'],
  },
]

export const sample_tags:Tag[] = [
  { name: 'All', count: 12 },
  { name: 'North Indian', count: 4 },
  { name: 'Breads', count: 2 },
  { name: 'Lunch', count: 10 },
  { name: 'Rice', count: 2 },
  { name: 'Salad', count: 2 },
  { name: 'South Indian', count: 2 },
  { name: 'Soup', count: 2 },
]
